--
-- File generated with SQLiteStudio v3.2.1 on ter fev 18 23:51:30 2020
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: TAB_CATEGORIA
DROP TABLE IF EXISTS TAB_CATEGORIA;

CREATE TABLE TAB_CATEGORIA (
    ID_CATEGORIA INTEGER      PRIMARY KEY AUTOINCREMENT,
    DESCRICAO    VARCHAR (50) 
);

-- Table: TAB_CONFIG
DROP TABLE IF EXISTS TAB_CONFIG;


-- Table: TAB_LANCAMENTO
DROP TABLE IF EXISTS TAB_LANCAMENTO;

CREATE TABLE TAB_LANCAMENTO (
    ID_LANCAMENTO   INTEGER       PRIMARY KEY,
    VALOR           DOUBLE (8, 2),
    DATA            DATETIME,
    DESCRICAO       VARCHAR (100),
    ID_CATEGORIA    INT           REFERENCES TAB_CATEGORIA (ID_CATEGORIA),
    TIPO_LANCAMENTO VARCHAR (1),
    QUITADA         VARCHAR (1),
    NROPARCELA      INT
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
